### ISSUE TITLE
Fehler in chrome Konsole (F12)

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.vis-canvas-gauges#21]
siehe:
https://forum.iobroker.net/topic/67996/neue-stable-versionen-der-adapter-web-socketio-und-ws/211?_=1713606124551

![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/b677a069-90b6-4e27-8b91-0a47553c48f9)

**Comment by bahnuhr** [comment]
und sowas kommt dann auch:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/0c408042-8d72-4916-be33-fa9299d1becc)

**Comment by Apollon77** [comment]
Kamnst Du bitte mal die Konfig zeigen

**Comment by bahnuhr** [comment]
konfig von gauge ?
Wenn ja, anbei:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/9f6481ce-0fd7-4405-9df1-8e3f00626c64)
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/687692e9-0f2b-47ea-8310-9b4a9e1fe963)
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/707bb4a8-3379-46c3-81ea-e918588bb79d)
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/a6cd1c82-91e3-48f2-b3d4-df7f7fd77302)

**Comment by bahnuhr** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/68fba4fd-6aa3-48c3-bf21-4da4f7b8c519)
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/f5238b3b-c8fa-4f89-8004-e98900a46c70)

**Comment by bahnuhr** [comment]
und die einzelnen widgets:
[Widget_Photovoltaik_alte Anlage.txt](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/files/15108926/Widget_Photovoltaik_alte.Anlage.txt)
[Widget_Photovoltaik_alte und neue Anlage.txt](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/files/15108927/Widget_Photovoltaik_alte.und.neue.Anlage.txt)
[Widget_Photovoltaik_neue Anlage.txt](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/files/15108928/Widget_Photovoltaik_neue.Anlage.txt)

**Comment by Apollon77** [comment]
Kannst Du bitte mal die beiden Bindings posten (max/Bis) Die eine Fehlermeldung sah für mich ein bissl nach einem Fehler im Binding aus ....

**Comment by bahnuhr** [comment]
hab ich schon alles durchgespielt. Wenn ich eine Zahl bei max eingebe kommt der Fehler auch (also ohne binding)

aber trotzdem:
{javascript.0.Geräte.Photovoltaik.Vis_Leistung_Kreis_max}
und Eigenschaften dieses DP:
{
  "common": {
    "type": "number",
    "name": "einstellen max für Kreis",
    "min": 0,
    "role": "per Script"
  },
  "native": {
    "type": "number",
    "name": "einstellen max für Kreis",
    "min": 0,
    "role": "per Script"
  },
  "type": "state",
  "from": "system.adapter.javascript.1",
  "user": "system.user.admin",
  "ts": 1697276696454,
  "_id": "javascript.0.Geräte.Photovoltaik.Vis_Leistung_Kreis_max",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by bahnuhr** [comment]
und dieses kam eben auch wieder:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/3055025a-adf5-4741-8107-7e2c7244482e)

**Comment by oweitman** [comment]
bitte mal noch die version des genutzten vis adapters und js-controllers (iobroker)

**Comment by bahnuhr** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/461069f5-e7f5-4497-a41d-114e4584072a)
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/f4c7d80b-fcf9-42dc-875d-3226fa633349)

**Comment by bahnuhr** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/b308f387-d0a4-497e-8d4e-11635ca80dd0)

**Comment by Apollon77** [comment]
mit ging es um das Bilding  mit neu-alt-gesamt ... ist das auch nur dieser name in {} oder mehr logik im binding?

**Comment by bahnuhr** [comment]
ne, nur de Name des DP steht da drin.

**Comment by oweitman** [comment]
den fehler konnte ich aktuell unter noch nicht nachvollziehbaren Bedingungen erzeugen.
ich muss noch ein wenig rumspielen. 
bei mir erschien er in der funktion animate. in deinen angaben gab es animate und drawX.
wahrscheinlich liegt es daran, das werte nicht korrekt weitergereicht werden.
schau mer mal. heute aber nicht mehr

wenn er bei dir nochmal auftaucht. könntest du mir bitte die komplette fehlermeldung inklusive dem ganzen stack trace mal als text kopieren. im screenshot sieht man immer nur den anfang
kann ich auch davon ausgehen, das max sich nicht so oft ändert, sondern einfach nur der anzeigewert?

**Comment by bahnuhr** [comment]
> komplette fehlermeldung inklusive dem ganzen stack trace

Was ist das und wo ? (browser konsole mit F12)


> text kopieren

kein Problem

> das max sich nicht so oft ändert,

Ich rufe die Werte minütlich ab. Und dann läuft ein Script. Und je nach Leistung, dann ...
Auszug:
`            var Leistung = getState(java+"2023_Leistung_alt_neu_gesamt").val;
            if (Leistung > 11500) { setState(java+"Vis_Leistung_Kreis_max",15000);
            } else if (Leistung > 9500) { setState(java+"Vis_Leistung_Kreis_max",12000);
            } else { if ( getState(java+"Vis_Leistung_Kreis_max").val != 10000 ) { setState(java+"Vis_Leistung_Kreis_max",10000) } };
`

**Comment by oweitman** [comment]
Ja genau die Fehlermeldung aus der Browser Konsole mit F12
Bisher hast du da immer nur Screenshots gemacht.

**Comment by bahnuhr** [comment]
anbei die Meldung:
`Uncaught TypeError: Cannot read properties of null (reading 'drawX')
    at t.value (gauge.min.js:2660:45)
    at e.options.value.options.animation.options.value (gauge.min.js:1661:28)
    at a (gauge.min.js:367:13)
    at gauge.min.js:521:24
`

![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/de5bdfee-6eab-4446-ada3-6fd835f03524)

anders hat es nicht geklappt.
noch ne Idee ?

**Comment by bahnuhr** [comment]
jetzt nochmal so:

`<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(252, 235, 235); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" role="link" tabindex="-1" title="http://192.168.243.15:8082/source/gauge.min.js:2660" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">gauge.min.js:2660</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of null (reading 'drawX')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at t.value (<button class="devtools-link text-button link-style" role="link" tabindex="-1" title="http://192.168.243.15:8082/source/gauge.min.js:2660:45" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">gauge.min.js:2660:45</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at e.options.value.options.animation.options.value (<button class="devtools-link text-button link-style" role="link" tabindex="-1" title="http://192.168.243.15:8082/source/gauge.min.js:1661:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">gauge.min.js:1661:28</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at a (<button class="devtools-link text-button link-style" role="link" tabindex="-1" title="http://192.168.243.15:8082/source/gauge.min.js:367:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">gauge.min.js:367:13</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <button class="devtools-link text-button link-style" role="link" tabindex="-1" title="http://192.168.243.15:8082/source/gauge.min.js:521:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">gauge.min.js:521:24</button></span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(252, 235, 235); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 653.891px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | value | @ | gauge.min.js:2660
-- | -- | -- | --
  | e.options.value.options.animation.options.value | @ | gauge.min.js:1661
  | a | @ | gauge.min.js:367
  | (anonym) | @ | gauge.min.js:521
  | requestAnimationFrame (async) |   |  
  | value | @ | gauge.min.js:520
  | set | @ | gauge.min.js:1658
  | updateGauge | @ | index.html:3764
  | t.dispatch | @ | can.custom.min.js:18
  | stop | @ | can.custom.min.js:44
  | _setAttrs | @ | can.custom.min.js:48
  | attr | @ | can.custom.min.js:48
  | updateState | @ | vis.js:3055
  | (anonym) | @ | vis.js:3781
  | (anonym) | @ | vis.js:4004
  | setTimeout (async) |   |  
  | _setTimeout | @ | vis.js:4003
  | onUpdate | @ | vis.js:3780
  | (anonym) | @ | conn.js:465
  | (anonym) | @ | socket.io.js:237
  | socket.onmessage | @ | socket.io.js:237

</span></div>
</body>
</html>`

**Comment by bahnuhr** [comment]
eben wieder Fehler:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/f75012e0-1013-4077-86fc-17f921a6676d)

wenn ich rechts klicke kommt:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/92b2f40f-e192-4f97-9471-40a4a2fd4867)

Hier ist der rechte Teil auch rot unterstrichen.

**Comment by bahnuhr** [comment]
So,
habe mal testweise o.g. Script auskommentiert. Fazit: Abfrage und einstellung von max ist nicht mehr gelaufen.
Fazit:
Es kommt nicht mehr zur Fehlermeldung bei F12 in der Konsole. Datenpunkte werden aktualisiert.

Dann, testweise ein einfaches Script geschrieben:
`   
                var java = "javascript.0.Geräte.Photovoltaik.";
                var Leistung = getState(java+"2023_Leistung_alt_neu_gesamt").val;
                var Kreis = getState(java+"Vis_Leistung_Kreis_max").val;
                Leistung = 9000;
                if (Leistung > 11500) { 
                    if ( Kreis != 15000 ) setState(java+"Vis_Leistung_Kreis_max",15000);
                } else if (Leistung > 9500) { 
                    if ( Kreis != 12000 ) setState(java+"Vis_Leistung_Kreis_max",12000);
                } else { 
                    if ( Kreis != 10000 ) setState(java+"Vis_Leistung_Kreis_max",10000);
                };
`
Und folglich kam der Fehler wieder. Aber auch nicht immer (das ist komisch daran).
Fazit:
Für mich sieht es derzeit wie folgt aus:
binding mit DP in Gauge max scheint nicht das Problem zu sein.
Wenn man diesen DP "max" dann aber per Script ändert scheint dies "manchmal" (?) nicht zu funktionieren.
Warum, wieso eine DP Änderung per Script beim gauge einen Fehler erzeugt weiß ich nicht.

@Apollon77 
@oweitman 
Vielleicht hilfts bei der Fehlersuche.

mfg
Dieter

**Comment by oweitman** [comment]
Ich habe mir mal den code des widgets, sowie der zugrundeliegenden bibliothek angeschaut.
da ich es aktuell noch nicht verlässlich reproduzieren konnte (ich muss da mal ein skript schreiben), habe ich dennoch eine
Ahnung warum der Fehler kommt.
Es wird sich wahrscheinlich um eine sogenannte race-condition handel. dazu muss man verstehen wie vis insbesondere mit den bindings funktioniert.
um das bei dir zu bestätigen, ersetze bitte das binding für den maxwert mit einem fixen wert. dann dürfte der fehler nicht mehr auftreten.
das binding im maxwert sorgt dafür, das bei Änderung der htmlteil zum widget aus vis gelöscht wird und neu angelegt wird.
wahrscheinlich wird der noch vorhandene prozess zur Animation aber nicht sauber beendet, so das bei Aktualisierung der Animation auf einen nicht mehr existenten canvas zugegriffen wird.
dadurch resultieren die unterschiedlichen fehler wie bspw nicht vorhandenes drawX oder animate, welches alles eigenschaften sind, die durch die canvas-gauge bibliothek individuell dem standardobjekt canvas hinzugefügt wird.
beheben könnte man das (muss mal testen), das vor dem zerstören des widgets noch die animation gestoppt wird.
der fehler deshalb nur sporadisch auf, da wie gesagt, eine änderung des max-wertes, sowie fast zeitgleich eine änderung des wertes stattfindet, was dann eine animation auslöst.

mal noch eine Zusatzfrage. Haben die Fehlermeldungen negative Auswirkungen? oder stören dich einfach nur die Fehlermeldungen in der Browserkonsole? Wenn es nur optik ist, müsste man das nicht beheben.

ich habe gerade mal noch deinen letzten text gelesen. also du hast max mit einem fixen wert ersetzt? oder einfach nicht mehr aktualisiert? und dann kommen keine fehler mehr?

**Comment by bahnuhr** [comment]
Ziel war es:
abhängig von der W die gauge im max Wert zu verändern.
Also wenn die Sonneneinstrahlung unter 10.000 W dann zeige immer 10.000 W als max Wert. Wenn die Sonne mehr produziert dann Ausweitung der gauge auf 12.000 oder 15.000.
Und dafür war das Script.

Und ja, wenn das Script lief, dann der Fehler bei F12 und einzelne DP haben sich nicht mehr aktualisiert. Faktisch wurden dann die Produktionszahlen der Sonne eingefrieren.
Thema im thread: "Meine Werte frieren ein !"

Und ja, dadurch erhebliche negative Auswirkungen. 

Und wie oben geschrieben; wenn ich den Wert max verändere (durch Script) dann kamen die Fehler. Läuft das Script nicht, dann passen die Werte. Max wird ja dann auch nicht geändert.

Wäre super, wenn du dies ändern könntest.
Danke im Voraus.

**Comment by oweitman** [comment]
ok testszenario aufgebaut.
fehler kann nachvollzogen werden
behebungsversuche erfolgen in den nächsten tagen

**Comment by bahnuhr** [comment]
Danke schön.
Und viel Erfolg bei der Klärung und Beseitigung des bugs.

**Comment by oweitman** [comment]
ok,
es sieht so aus als ob es einen workaround ohne code-änderung gibt.
lösche bitte das binding aus dem Abschnitt
Sektoren[0]
Am beste deaktivierst du den Abschnitt komplett. Es scheint auch das du ihn nicht nutzt.
Das mehrfache eintragen eines bindings führt auch zu dem Fehler, da vis dann einfach für jede Änderung
eine komplette Entfernung und Neuhinzufügen des jeweiligen gauge-Objekts veranlasst.
Im parallel läuft aber noch die Aktualisierung des Zeigers.
Die bibliohtek beendet eigentlich auch alles richtig, aber es scheint da doch Situationen vorzukommen,
die in der Bibliothek nicht abgebildet sind.
Leider wird die zugrundeliegende Bibliothek (also nicht das iobroker widget selbst, seit einigen jahren nicht mehr gepflegt.
Daher ist nicht mit einer grundlegenden Überarbeitung zu rechnen).
https://github.com/Mikhus/canvas-gauges
Auch gibt es bereits mehrere Forks die einzelne Probleme angegangen sind, aber keinen, bei dem man sagen könnte, der könnte als stabile Basis wiede4r verwendet werden.

getestet habe ich es mit einem skript welches alle 500ms den wert
und alle 5000ms den max-wert ändert und habe keine neuen abbrüche mehr gehabt

**Comment by bahnuhr** [comment]
> Am beste deaktivierst du den Abschnitt komplett. Es scheint auch das du ihn nicht nutzt.

Doch, wird genutzt. Denn durch diesen Eintrag wird ja die Farbe des Sektors bestimmt. Deaktiviere ich den Sektor dann kommt keine Farbe mehr bei den ticks.
Aber damit muss ich wohl jetzt leben.

Danke für eure Mühe beim Suchen des Problems. Zumindest ist jetzt erkannt wo das Problem lag.

Und Schade, dass man keinen Workaround hat.

Du schreibst, es gibt mehrere Forks. Auch zu diesem Problem?
Wäre es möglich per JS den Max Wert bei den Sektoren per Script irgendwo rein zu schreiben ?

mfg
Dieter

**Comment by bahnuhr** [comment]
Sektor x ist raus.

Fehler kam eben trotzdem wieder:
![image](https://github.com/ioBroker/ioBroker.vis-canvas-gauges/assets/25694404/5a459efa-187b-4112-bb2c-1e9f66d9c33d)
